stages:
  - compile_package
  - sonarqube-check
  - build_image
  - container_scanning
  - push_helm

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  CHART_REPO: gitops
  BRANCH_NAME: java

compile:
  stage: compile_package
  image: maven
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  tags:
    - test
  only:
    - main

sonarqube-check:
  stage: sonarqube-check
  image: maven:3-eclipse-temurin-17
  script: 
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
  tags:
    - test

build:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  tags:
    - test
  only:
    - main

container_scanning:
  stage: container_scanning
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$CI_REGISTRY_USER"
    TRIVY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}
  script:
    - trivy --version
    - time trivy image --download-db-only
    - time trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 0 "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 1 --severity CRITICAL "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when:                          always
    reports:
      container_scanning:          gl-container-scanning-report.json
    expire_in: 1 week
  allow_failure: true 
  tags:
    - test
  only:
    - main

push_helm:
  stage: push_helm
  image: bitnami/git
  script:
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git clone https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.com/tahirbalayarov/$CHART_REPO.git -b $BRANCH_NAME
    - cd $CHART_REPO
    - sed -i "s/tag:.*/tag:\ $CI_COMMIT_SHORT_SHA/g" values.yaml
    - git commit -am "change image tag to $CI_COMMIT_SHORT_SHA"
    - git remote -v
    - git push origin $BRANCH_NAME
  tags:
    - test
  only:
    - main