apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-deploy
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - image: {{ .Values.deployment.containers.repository }}:{{ .Values.deployment.containers.tag }}
        name: {{ .Values.app }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.deployment.containers.env.spring_profiles_active }}
        resources:
          requests:
            memory: {{ .Values.deployment.containers.resources.request.memory }}
            cpu: {{ .Values.deployment.containers.resources.request.cpu }}
          limits:
            memory: {{ .Values.deployment.containers.resources.limits.memory }}
            cpu: {{ .Values.deployment.containers.resources.limits.cpu }}
        ports:
          - containerPort: {{ .Values.deployment.containers.port }}
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets }}