apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry_secret.registry_url (printf "%s:%s" .Values.registry_secret.username .Values.registry_secret.password | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson