app: java

deployment:
  replicas: 2
  containers:
    repository: registry.gitlab.com/tahirbalayarov/java_app
    tag: fbe88f61
    env:
      spring_profiles_active: prod
    resources:
      request:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "512m"
    port: 8080
  imagePullSecrets: registry-secret

service:
  type: ClusterIP
  port: 80
  targetport: 8080

ingress:
  cluster_issuer: letsencrypt-prod
  ingressClassName: nginx
  tls:
    hosts: "*.tahirvibe.me"
  rules:
    host: "java.tahirvibe.me"
    path: "/"
    pathType: Prefix
    port: 80

hpa:
  averageUtilization: 80
  maxReplicas: 4
  minReplicas: 2
  